collections:
  posts:
    output: true
    permalink: /news/:year-:month-:day-:title/
  features:
    output: true

defaults:
  - scope:
      path: ""
      type: "features"
    values:
      layout: "feature"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:title/

plugins:
  - jekyll-mentions

webrick:
  headers:
    Content-Security-Policy: script-src 'self' 'unsafe-inline' https://www.google-analytics.com; base-uri 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff